config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :challenges
    resources :points, except: [:show, :index]
    root :to => "dashboard#index"

    devise_for :users, controllers: { sessions: "sessions" }
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
      put 'users/update_levelup' => 'users#update_levelup', :as => 'user_update_levelup', :defaults =>{:format => :js}
    end
    devise_for :participants, only: [:confirmations], controllers: { confirmations: 'confirmations' }
    resources :dashboard, only: [:index]
  end

  get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '', to: redirect("/#{I18n.default_locale}")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  has_and_belongs_to_many :participants

  accepts_nested_attributes_for :participants, reject_if: :all_blank, allow_destroy: true

  validates :name, :start_date, :end_date, presence: true
end

app/models/participant.rb
class Participant < User
  has_and_belongs_to_many :challenges

  devise :confirmable

  before_validation :set_random_password

  private
    def set_random_password
      self.password = SecureRandom.hex(4) if self.password.blank?
    end
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user
  belongs_to :challenge

  validates :user, :challenge, :punctuation_date, presence: true
  validates :punctuation_date, uniqueness: {scope: :user_id, message: I18n.t('activerecord.errors.models.point.punctuation_date')}
  validates_with Validators::PointValidator

  after_save :check_user_rank

  def sum_points
    train + food_plan + coaching + sleep + surprise
  end

  private
    def check_user_rank
      new_rank = ranks(user.total_points)

      if new_rank > User.ranks[user.rank]
        user.update_rank(new_rank)
      elsif new_rank != User.ranks[user.rank]
        user.update_attribute(:rank, new_rank)
      end
    end

    def ranks(points)
      case points
      when 0..14
        return User.ranks[:moises]
      when 15..29
        return User.ranks[:trainee]
      when 30..44
        return User.ranks[:adapted]
      when 45..59
        return User.ranks[:scaled]
      when 60..89
        return User.ranks[:rx]
      when 90..119
        return User.ranks[:myth]
      when 120..160
        return User.ranks[:hero]
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :validatable, :trackable,
    :recoverable
  has_many :points, dependent: :destroy

  validates :name, presence: true

  scope :admins, ->(admin) { where(admin: admin) }

  enum rank: {moises: 0, trainee: 1, adapted: 2, scaled: 3, rx: 4, myth: 5, hero: 6}

  def total_points
    points.map{|p| p.sum_points}.sum
  end

  def update_rank(new_rank)
    self.rank = new_rank
    self.levelup = true

    save
  end
end

app/models/validators/point_validator.rb
module Validators
  class PointValidator < ActiveModel::Validator
    def validate(record)
      unless record.sum_points > 0
        record.errors[:base] << I18n.t('activerecord.errors.models.point.no_points')
      end

      unless record.challenge.nil?
        unless record.punctuation_date.between?(record.challenge.start_date, record.challenge.end_date)
          record.errors[:punctuation_date] << "#{I18n.t('activerecord.errors.models.point.out_of_range')} (#{I18n.l(record.challenge.start_date)} - #{I18n.l(record.challenge.end_date)})"
        end
      end
    end
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder

  protect_from_forgery with: :exception

  respond_to :html

  around_action :with_locale
  before_action :authenticate_user!

  layout :set_layout

  private
    def set_layout
      user_signed_in? ? 'application' : 'login'
    end

    def with_locale
      I18n.with_locale(params[:locale]) { yield }
    end

    def default_url_options(options = {})
      { locale: I18n.locale }
    end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]

  # GET /challenges
  def index
    @challenges = Challenge.all
    respond_with(@challenges)
  end

  # GET /challenges/1
  def show
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
    respond_with(@challenge)
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges
  def create
    @challenge = Challenge.new(challenge_params)

    @challenge.save
    respond_with(@challenge, location: challenges_path)
  end

  # PATCH/PUT /challenges/1
  def update
    @challenge.update(challenge_params)
    respond_with(@challenge, location: challenges_path)
  end

  # DELETE /challenges/1
  def destroy
    @challenge.destroy
    respond_with(@challenge)
  end

  private
    def set_challenge
      @challenge = Challenge.includes(:participants).find(params[:id])
    end

    def challenge_params
      params.require(:challenge).permit(:name, :start_date, :end_date, participants_attributes: [:id, :name, :email, :_destroy])
    end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private
    def after_confirmation_path_for(resource_name, resource)
      new_user_session_path
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @point = Point.new
    @points = current_user.points.all.order(:punctuation_date)
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :set_challenge, only: [:edit, :update, :destroy]

  # GET /points
  # def index
  #   @points = current_user.points.all.order(:punctuation_date)
  #   respond_with(@points)
  # end

  # GET /points/new
  def new
    @point = Point.new
    respond_with(@point)
  end

  # GET /points/1/edit
  def edit
  end

  # POST /points
  def create
    @point = Point.new(point_params)

    @point.user = current_user
    @point.challenge = Challenge.first

    @point.save

    respond_with(@point, location: dashboard_index_path)
  end

  # PATCH/PUT /points/1
  def update
    @point.update(point_params)
    respond_with(@point, location: dashboard_index_path)
  end

  # DELETE /points/1
  def destroy
    @point.destroy
    respond_with(@point, location: dashboard_index_path)
  end

  private
    def set_challenge
      @point = Point.find(params[:id])
    end

    def point_params
      params.require(:point).permit(:punctuation_date, :train, :food_plan, :coaching, :sleep, :surprise, :obs)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  self.responder = ActionController::Responder

  def after_sign_in_path_for(resource)
    return edit_user_registration_path if resource.sign_in_count == 1

    root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update_levelup
    return render json: {success: true}, status: 200 if current_user.update({levelup: false})

    return render json: {error: true}, status: 422
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_actived_menu(controllers, action=nil)
    active = nil
    action.nil? ? (active = 'active' unless !controllers.include?(params[:controller])) :
      (active = 'active' if controllers.include?(params[:controller]) and action.include?(params[:action]))

    return active
  end

  def present(model)
    klass = "#{model.class}Presenter".constantize
    klass.new(model)
  end

  def normalize_flash_keys(key)
    case key
    when "notice"
      key = "success"
    when "alert"
      key = "error"
    else
      key
    end
  end

  def truncate_content_tag(tag, description, truncate)
    return "" if description.blank?
    options = {:title=>description } if description.length >truncate
    content_tag(tag, description.truncate(truncate), options)
  end
end

app/views/application/_congratz_message.html.slim
#congratzModal.modal.fade aria-hidden="true" aria-labelledby="formModalLabel" role="dialog" tabindex="-1" data-url="#{user_update_levelup_path}"
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  &times;
        h4#formModalLabel.modal-title = t("messages.congratz_title")
        .modal-body
          .row
            .col-sm-12
              = raw t("messages.congratz", rank: I18n.t("activerecord.attributes.user.ranks.#{current_user.rank}"))
        .modal-footer
          button.btn.btn-raised.btn-success.ink-reaction data-dismiss="modal" type="button" = t("actions.thanks")

app/views/application/_flash_toasters.html.slim
- flash.each do |key, value|
  - key = normalize_flash_keys(key)
  javascript:
    toastr["#{key}"]("#{value}")

app/views/application/_head.html.slim
meta charset="utf-8"
meta content="IE=edge" http-equiv="X-UA-Compatible"
meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no"
meta name="keywords" content= t('app_keywords')
meta name="description" content= t('app_description')

title
  = page_title(app_name: t("app_name"))

= stylesheet_link_tag 'roboto', 'application', media: 'all', 'data-turbolinks-track' => true
= javascript_include_tag 'application', 'data-turbolinks-track' => true
= javascript_include_tag "bootstrap-tour/translations/change-password_#{I18n.locale}"
= javascript_include_tag "bootstrap-tour/translations/dashboard_#{I18n.locale}"
= csrf_meta_tags

/![if lt IE 9]
= javascript_include_tag 'html5shiv.min'

app/views/application/_header.html.slim
header#header
  .headerbar
    .headerbar-left
      ul.header-nav.header-nav-options
        li.header-nav-brand
          .brand-holder
            = link_to root_path do
              span.text-lg.text-bold.text-primary
                = t("app_name")
        - if current_user.admin?
          li
            = link_to "javascript:void(0);", class: "btn btn-icon-toggle menubar-toggle", "data-toggle" => "menubar" do
              i.fa.fa-bars
    -if user_signed_in?
      .headerbar-right
        ul.header-nav.header-nav-profile
          li.dropdown
            = link_to "javascript:void(0);", class: "dropdown-toggle ink-reaction", "data-toggle"=>"dropdown" do
              span.profile-info
                = current_user.name
                small = current_user.admin? ? t("admin") : Participant.model_name.human(count: 1)
            ul.dropdown-menu.animation-dock
              li
                = link_to t("actions.change_password"), edit_user_registration_path
              li
                = link_to t("actions.logout"), destroy_user_session_path, method: :delete

app/views/application/_menubar.html.slim
#menubar.menubar-inverse
  .menubar-fixed-panel
    div
      = link_to "javascript:void(0);", class: "btn btn-icon-toggle btn-default menubar-toggle", "data-toggle" => "menubar" do
        i.fa.fa-bars
    .expanded"
      = link_to root_path do
        span.text-lg.text-bold.text-primary
          = t("app_name")
  .menubar-scroll-panel
    ul#main-menu.gui-controls
      li class="#{set_actived_menu('dashboard', 'index')} dashboard"
        = link_to dashboard_index_path do
          .gui-icon
            i.md.md-home
          span.title Dashboard
      - if current_user.admin?
        li class=set_actived_menu('challenges')
          = link_to challenges_path do
            .gui-icon
              i.md.md-web
            span.title Desafios
      - else
        li class="#{set_actived_menu('points')} points"
          = link_to points_path do
            .gui-icon
              i.md.md-assessment
            span.title Pontos
    .menubar-foot-panel
      small.no-linebreak.hidden-folded
        span.opacity-75 Copyright &copy; 2016 &nbsp;
        strong = t("app_name")

app/views/challenges/_form.html.slim
= simple_form_for(@challenge) do |f|
  .card-body
    - unless f.error_notification.nil?
      .alert.alert-danger
        = f.error_notification
    .row
      .col-sm-6
        = f.input :name, autofocus: true
    .row
      .col-sm-3
        = f.input :start_date, as: :string, input_html: {class: "date", value: present(@challenge).format_start_date}
      .col-sm-3
        = f.input :end_date, as: :string, input_html: {class: "date", value: present(@challenge).format_end_date}
    .card.card-underline
      .card-head.card-head-sm.style-primary
        header
          h3 =Participant.model_name.human(count: 2)
      #participants-fields.card-body
        = f.simple_fields_for :participants do |participant|
          = render 'participant_fields', f: participant
        .links
          = link_to_add_association t("actions.add_participant"), f, :participants, class: "btn btn-raised active btn-success ink-reaction"
  .card-actionbar
    .card-actionbar-row
      .pull-left
        = link_to t("actions.back"), challenges_path, class: "btn btn-raised btn-info ink-reaction"
      .pull-right
        = f.button :submit, class: "btn-raised btn-success ink-reaction"

app/views/challenges/_participant_fields.html.slim
.nested-fields
  .row
    .col-sm-5
      = f.input :name
    .col-sm-5
      = f.input :email
    .col-sm-2
      = link_to_remove_association f, class: "btn ink-reaction btn-floating-action btn-danger" do
          i.fa.fa-trash-o

app/views/challenges/edit.html.slim
.card.card-underline
  .card-head.card-head-sm.style-primary
    header
      h3 =t('challenges.update.title')
  = render "form"

app/views/challenges/index.html.slim
.card.card-underline
  .card-head.card-head-sm.style-primary
    header
      h3 = "#{Challenge.model_name.human(count: 2)}"
    header.pull-right
      h3 = link_to "#{t("actions.new")} #{Challenge.model_name.human(count: 1)}", new_challenge_path

  .card-body
    - if @challenges.any?
      div.table-responsive
        table.table.no-margin.table-striped
          thead
            tr
              th Nome
              th Data de Início
              th Data de Término
              th.text-right Ações
          tbody
            - @challenges.each do |challenge|
              tr
                td = challenge.name
                td = present(challenge).format_start_date
                td = present(challenge).format_end_date
                td.text-right
                  = link_to edit_challenge_path(challenge), class: "btn btn-icon-toggle", data: {toggle: "tooltip", placement: "top", :"original-title" => "#{t("actions.edit")}"} do
                    i.fa.fa-pencil
                  = link_to challenge_path(challenge), method: :delete, class: "btn btn-icon-toggle", data: {toggle: "tooltip", placement: "top", :"original-title" => "#{t("actions.delete")}", :confirm => t("messages.destroy")} do
                    i.fa.fa-trash-o
    - else
      h2.text-light.text-center = t("messages.no_records", resource: Challenge.model_name.human(count: 2).downcase)

app/views/challenges/new.html.slim
.card.card-underline
  .card-head.card-head-sm.style-primary
    header
      h3 =t('challenges.create.title')
  = render "form"

app/views/challenges/show.html.slim
p#notice = notice

p
  strong Name:
  = @challenge.name
p
  strong Start date:
  = @challenge.start_date
p
  strong End date:
  = @challenge.end_date

= link_to 'Edit', edit_challenge_path(@challenge)
'|
= link_to 'Back', challenges_path

app/views/dashboard/_admin.html.slim
.col-md-3.col-sm-6
  .card
    .card-body.no-padding
      .alert.alert-callout.alert-info.no-margin
        strong.text-xl 2
        br
        span.opacity-50 Total de participantes
        .stick-bottom-left-right
          .height-2.sparkline-revenue

app/views/dashboard/_participant.html.slim
.row
  .col-md-6.col-sm-6.rank
    .card
      .card-body.no-padding
        .alert.alert-callout.alert-info.no-margin
          #morris-donut-graph-rank.size-6.center-elements data-colors="#A5B6B7,#D3793D,#3DA3F3,#20D4C9,#FFAE36,#E05142,#BF7ADC"
          span.opacity-50 = "Rank"
  .col-md-6.col-sm-6.points
    .card
      .card-body.no-padding
        .alert.alert-callout.alert-success.no-margin
          .text-center
            .knob.knob-default-light-track.size-6.center-elements style="color: #{present(@point).format_rank(current_user.total_points).last};"
              input type="text" class="dial" value=current_user.total_points data-min="0" data-max="160" data-readOnly="true" data-angleOffset=-125 data-angleArc=250
          span.opacity-50 = "#{I18n.t('labels.personal_rank')} - #{present(@point).format_rank(current_user.total_points).first}"
.row
  .col-md-12.col-sm-12.general-rank
    .card
      .card-body.no-padding
        .alert.alert-callout.alert-info.no-margin
          table.table.no-margin
            thead
              tr
                th #
                th = I18n.t('activerecord.models.participant', {count: 1})
                th = I18n.t('activerecord.models.point', {count: 2})
                th Rank
            tbody
              - Challenge.first.participants.includes(:points).sort_by(&:total_points).reverse.each_with_index do |participant, idx|
                tr style="background-color: #{present(@point).format_rank(participant.total_points).last};"
                  td = idx+1
                  td = truncate_content_tag(:span, participant.name, 25)
                  td = participant.total_points
                  td = present(@point).format_rank(participant.total_points).first
          span.opacity-50 = I18n.t('labels.general_rank')
.row
  .col-md-12.col-sm-12.participant-points
    .card
      .card-body.no-padding
        .alert.alert-callout.alert-success.no-margin
          = render :partial => "points/index"
          span.opacity-50 = I18n.t('labels.saved_points')
= link_to "#", class: "add-points btn ink-reaction btn-floating-action btn-success", data: {toggle: "modal", target: "#pointsModal"} do
  i.fa.fa-check
= render :partial => "points/modal_form"

app/views/dashboard/index.html.slim
= render :partial => current_user.admin? ? "admin" : "participant"

app/views/layouts/application.html.slim
doctype 5
html lang="pt"
  head
    = render 'head'

  / menubar-hoverable header-fixed menubar-pin
  body class="#{body_class}"
    javascript:
      I18n.defaultLocale = "#{I18n.default_locale}";
      I18n.locale = "#{I18n.locale}";
    = render 'header'
    #base
      #content
        section
          .section-body
            .row
              .col-sm-12
                = render 'flash_toasters'
                = yield
        - if current_user.levelup?
          = render 'congratz_message'
      - if current_user.admin?
        = render 'menubar'

app/views/layouts/login.html.slim
doctype 5
html lang="pt"
  head
    = render 'head'

  body class=body_class
    javascript:
      I18n.defaultLocale = "#{I18n.default_locale}";
      I18n.locale = "#{I18n.locale}";
    section class="section-account"
      .img-backdrop
      .spacer
      .card.contain-sm.style-transparent
        .card-body
          .row
            .col-sm-8
              h1.text-bold.text-primary
                = t("app_name")
              = render 'flash_toasters'
              = yield

app/views/points/_form.html.slim
= simple_form_for(@point) do |f|
  .card-body
    - unless f.error_notification.nil?
      .alert.alert-danger
        = f.error_notification
        ul
          - f.object.errors[:base].each do |error|
            li = error
    .row
      .col-sm-12
        = f.input :train, as: :boolean, wrapper: false, label: false do
          label.checkbox-inline.checkbox-styled
            = f.check_box :train, {}, 3, 0
            span = t("activerecord.attributes.point.train")


        = f.input :food_plan, as: :boolean, wrapper: false, label: false, input_html: {data: {label: t("activerecord.attributes.point.food_plan")}}
        = f.input :coaching, as: :boolean, wrapper: false, label: false, input_html: {data: {label: t("activerecord.attributes.point.coaching")}}
    .row
      .col-sm-12
        = f.input :sleep, as: :boolean, wrapper: false, label: false, input_html: {data: {label: t("activerecord.attributes.point.sleep")}}
        label.checkbox-inline.checkbox-styled
          input type="checkbox" id="points_surprise_challenge"
          span = t("activerecord.attributes.point.surprise")
    .row.surprise-points
      .col-sm-12
        = f.input :surprise, as: :string, input_html: {maxlength: 1, data: {inputmask: "'mask': '9'"}}, hint: I18n.t('hints.surprise_points')
    br
    .row
      .col-sm-12
        = f.input :punctuation_date, as: :string, input_html: {class: "date", value: present(@point).format_punctuation_date}
    .row
      .col-sm-12
        = f.input :obs, input_html: {maxlength: 100}, hint: t("hints.maxlength", count: 100)
  .card-actionbar
    .card-actionbar-row
      .pull-left
        = link_to t("actions.back"), dashboard_index_path, class: "btn btn-raised btn-info ink-reaction"
      .pull-right
        = f.button :submit, class: "btn-raised btn-success ink-reaction"

app/views/points/_index.html.slim
- if @points.any?
  div.table-responsive
    table.table.no-margin.table-striped
      thead
        tr
          th = I18n.t('labels.date')
          th = I18n.t('activerecord.models.point', {count: 2})
          th.text-right = I18n.t('labels.actions')
      tbody
        - @points.each do |point|
          tr
            td = present(point).format_punctuation_date
            td = point.sum_points
            td.text-right
              = link_to edit_point_path(point), class: "btn btn-icon-toggle", data: {toggle: "tooltip", placement: "top", :"original-title" => "#{t("actions.edit")}"} do
                i.fa.fa-pencil
              = link_to point_path(point), method: :delete, class: "btn btn-icon-toggle", data: {toggle: "tooltip", placement: "top", :"original-title" => "#{t("actions.delete")}", :confirm => t("messages.destroy")} do
                i.fa.fa-trash-o
- else
  h2.text-light.text-center = t("messages.no_records", resource: Point.model_name.human(count: 2).downcase)

app/views/points/_modal_form.html.slim
#pointsModal.modal.fade aria-hidden="true" aria-labelledby="formModalLabel" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  &times;
        h4#formModalLabel.modal-title = t("points.create.title")
      - @point = Point.new
      = simple_form_for(@point) do |f|
        .modal-body
          .row
            .col-sm-12
              = f.input :train, as: :boolean, wrapper: false, label: false do
                label.checkbox-inline.checkbox-styled.tour-one
                  = f.check_box :train, {}, 3, 0
                  span = t("activerecord.attributes.point.train")


              = f.input :food_plan, as: :boolean, wrapper: false, label: false, input_html: {data: {label: t("activerecord.attributes.point.food_plan")}}
              = f.input :coaching, as: :boolean, wrapper: false, label: false, input_html: {data: {label: t("activerecord.attributes.point.coaching")}}
          .row
            .col-sm-12
              = f.input :sleep, as: :boolean, wrapper: false, label: false, input_html: {data: {label: t("activerecord.attributes.point.sleep")}}
              label.checkbox-inline.checkbox-styled.tour-two
                input type="checkbox" id="points_surprise_challenge"
                span = t("activerecord.attributes.point.surprise")
          .row.surprise-points
            .col-sm-12
              = f.input :surprise, as: :string, input_html: {maxlength: 1, data: {inputmask: "'mask': '9'"}}, hint: I18n.t('hints.surprise_points')
          br
          .row
            .col-sm-12
              = f.input :punctuation_date, as: :string, input_html: {class: "date", value: present(@point).format_punctuation_date}
          .row
            .col-sm-12
              = f.input :obs, input_html: {maxlength: 100}, hint: t("hints.maxlength", count: 100)
        .modal-footer
          button.btn.btn-raised.btn-info.ink-reaction data-dismiss="modal" type="button" = t("actions.cancel")
          = f.button :submit, class: "btn-raised btn-success ink-reaction"

app/views/points/edit.html.slim
.card.card-underline
  .card-head.card-head-sm.style-primary
    header
      h3 =t('points.update.title')
  = render "form"

app/views/points/new.html.slim
.card.card-underline
  .card-head.card-head-sm.style-primary
    header
      h3 =t('points.create.title')
  = render "form"